"use client"

import { useEffect, useState } from "react"
import { motion } from "framer-motion"
import DashboardToggle from "@/components/finance/DashboardToggle"
import StockTable from "@/components/finance/StockTable"
import StockChart from "@/components/finance/StockChart"
import type { StockWithHistory } from "@/app/data/types/finance"

export default function FinanceDashboard() {
  const [view, setView] = useState<"table" | "chart">("table")
  const [stocks, setStocks] = useState<StockWithHistory[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    fetch("/api/finance/stocks")
      .then((r) => r.json())
      .then((d) => setStocks(d.stocks ?? []))
      .catch((e) => setError(e.message))
      .finally(() => setLoading(false))
  }, [])

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="w-6 h-6 border-2 border-[#FF8000] border-t-transparent rounded-full animate-spin" />
      </div>
    )
  }

  if (error) {
    return (
      <div className="text-red-400 text-center py-12">
        Failed to load stock data: {error}
      </div>
    )
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 16 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4 }}
      className="space-y-6"
    >
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-white">Finance Dashboard</h1>
          <p className="text-zinc-500 text-sm mt-1">
            Daily stock analysis powered by Claude AI · Data updated after market close
          </p>
        </div>
        <DashboardToggle view={view} onChange={setView} />
      </div>

      {view === "table" ? (
        <StockTable stocks={stocks} />
      ) : (
        <StockChart stocks={stocks} />
      )}

      <p className="text-zinc-700 text-xs text-center">
        Analysis generated by Claude Haiku · Prices from Alpha Vantage / Yahoo Finance · Not financial advice
      </p>
    </motion.div>
  )
}
